name: expense_tracker
description: "A new Flutter project."

#---->Version : 3.19.5-stable

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  google_fonts: any
  rxdart: any
  firebase_core: any
  firebase_auth: any
  carousel_slider: any
  dots_indicator: any
  flutter_svg: any
  persistent_bottom_nav_bar_v2: any
  dotted_border: any
  permission_handler: any
  device_info_plus: any
  geolocator: any
  image_picker: any
  image_cropper: any
  intl: any
  firebase_database: any
  firebase_storage: any
  syncfusion_flutter_charts: ^25.2.4
  #https://github.com/syncfusion/flutter-widgets/issues/1870
  loading_animation_widget: any
  shimmer: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/third_party_icon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
