// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvUoptm6LBZ9zMkGVnMMmSyqm2ubup5ms',
    appId: '1:239676754306:web:4d2d2a82dce506d7f3279b',
    messagingSenderId: '239676754306',
    projectId: 'expense-tracker-a64ac',
    authDomain: 'expense-tracker-a64ac.firebaseapp.com',
    storageBucket: 'expense-tracker-a64ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJQA6BeXxDShWnHGk7Zs-IEXlsaYydZA0',
    appId: '1:239676754306:android:f41e8224b6e6a7bdf3279b',
    messagingSenderId: '239676754306',
    projectId: 'expense-tracker-a64ac',
    storageBucket: 'expense-tracker-a64ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2v1GnuNOkdWgWVh_rPRTkkMtA7YjEx8g',
    appId: '1:239676754306:ios:4da88717a418864ef3279b',
    messagingSenderId: '239676754306',
    projectId: 'expense-tracker-a64ac',
    storageBucket: 'expense-tracker-a64ac.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );
}
