/// Flutter icons CustomIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData settings_icons = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_bag_icons = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData show_icons = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_highest_lowest_icons = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_icons = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData success_icons = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transaction_icons = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_icons = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_icons = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_icons = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning_icons = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down_icons = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left_2_icons = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left_icons = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_icons = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attachment_icons = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_icons = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_icons = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_icons = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData create_icons = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData create_icons_2 = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData currency_exchange_icons = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_icons = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_icons = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery_icons = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expense_icons = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_icons = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData income_icons = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData line_chart_icons = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_horizontal_icons = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout_icons = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData new_icons = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_icons = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pie_chart_icons = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restaurant_icons = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recurring_bill_icons = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_icons = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData salary_icons = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_icon = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bonus_icon = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData interest_icon = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loan_icon = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData salary_icons_1 = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lottery_icon = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rent_icon = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData travel_icon = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bills_icon = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData education_icon = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData donation_icon = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food_icons = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health_icon = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fule_icon = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData groceries_icon = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData investment_icon = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
